### ISSUE TITLE
Labeler fails to execute due to typeError

### ISSUE THREAD

**Issue by kushthedude** [actions/labeler#88]
The action fails to execute 
```sh
1s
16
(node:2511) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
1
Run actions/labeler@master
4
(node:2511) UnhandledPromiseRejectionWarning: TypeError: (s || "").replace is not a function
5
    at escapeData (/home/runner/work/_actions/actions/labeler/master/dist/index.js:6454:10)
6
    at Command.toString (/home/runner/work/_actions/actions/labeler/master/dist/index.js:6448:35)
7
    at issueCommand (/home/runner/work/_actions/actions/labeler/master/dist/index.js:6411:30)
8
    at Object.issue (/home/runner/work/_actions/actions/labeler/master/dist/index.js:6415:5)
9
    at Object.error (/home/runner/work/_actions/actions/labeler/master/dist/index.js:10186:15)
10
    at /home/runner/work/_actions/actions/labeler/master/dist/index.js:4140:18
11
    at Generator.next (<anonymous>)
12
    at /home/runner/work/_actions/actions/labeler/master/dist/index.js:4099:71
13
    at new Promise (<anonymous>)
14
    at module.exports.198.__awaiter (/home/runner/work/_actions/actions/labeler/master/dist/index.js:4095:12)
15
(node:2511) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
16
(node:2511) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by dakale** [comment]
Should be fixed now, see https://github.com/actions/labeler/pull/95
